source 'https://rubygems.org' do
  gem 'pry'
  gem 'rgl'
  gem 'rspec'
  gem 'readapt'
  gem 'ruby-prof'
  gem 'immutable-ruby'
  gem 'ruby-progressbar'
  gem 'progress_bar'
  gem 'pqueue'
  gem 'guard-rspec', require: false
  gem 'rbs'
  gem 'rspec-parameterized'

  group :development, :test do
    gem 'ruby-debug-ide'
    gem 'debase', '>= 0.2.5.beta2'
  end

end
