source 'https://rubygems.org' do
  gem 'pry'
  gem 'rgl'
  gem 'rspec'
  gem 'readapt'
  gem 'ruby-prof'
  gem 'immutable-ruby'
  gem 'ruby-progressbar'
  gem 'progress_bar'
  gem 'pqueue'
  gem 'guard-rspec', require: false
end
