[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Frederik Nordahl Jul Sabroe <frederikns@gmail.com>"]
edition = "2018"

[features]


[dependencies]
itertools = "0.9.0"
grok = "1.1"
regex = "1"
lazy_static = "1.4.0"
